import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { BackgroundBlobs } from "./_components/background";
import { Footer } from "./_components/includes/footer";
import { Header } from "./_components/includes/header";
import { ThemeProvider } from "./_components/theme/theme-provider";

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className={`${montserrat.variable} antialiased relative`}>
				<BackgroundBlobs />
				<Header />
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
				<Footer />
			</body>
		</html>
	);
}
